# Reference outputs of the chemotaxis models with the pre-behaviors API.
# Run on commit 733ef48 (before the composable-behaviors refactor), from the repo root:
#   using MicrobeAgents; include("test/fixtures/generate_reference.jl")
# It will NOT run on later versions; test/regression.jl replays the same scenarios
# with the behaviors API and compares against the generated reference.jl.
using MicrobeAgents, Random

const L = 1000.0
const DT = 0.1
const NSTEPS = 300
const NAGENTS = 3

field(m, model) = 1.0 + 0.01 * position(m)[1] + 0.001 * abmtime(model) * DT
grad(m::AbstractMicrobe{D}, model) where {D} = SVector{D}(i == 1 ? 0.01 : 0.0 for i in 1:D)
ramp(m, model) = 0.001
const CHEMO = GenericChemoattractant{2}(;
    concentration_field = field,
    concentration_gradient = grad,
    concentration_ramp = ramp,
)

xpos(m) = position(m)[1]
ypos(m) = position(m)[2]
chemotaxis_bias(m) = bias(m)
chemotaxis_state(m) = m.state
state_m(m) = m.state_m
state_z(m) = m.state_z

const RT = () -> RunTumble([30.0], 1.0, Isotropic(2); tumble_duration = 0.1)
const RRF = () -> RunReverseFlick([46.5], 0.45, [46.5], 0.45)

const SCENARIOS = [
    ("BrownBerg", BrownBerg{2}, RT, (rotational_diffusivity = 0.035, radius = 0.5), []),
    ("Brumley", Brumley{2}, RRF,
        (rotational_diffusivity = 0.035, radius = 0.5, chemotactic_precision = 6.0), []),
    ("Celani", Celani{2}, RT,
        (rotational_diffusivity = 0.26, radius = 0.5, chemotactic_precision = 6.0), []),
    ("Xie", Xie{2}, RRF,
        (rotational_diffusivity = 0.26, radius = 0.5, chemotactic_precision = 6.0),
        [state_m, state_z]),
    ("SonMenolascina", SonMenolascina{2},
        () -> RunReverseFlick([30.0], 0.5, [30.0], 0.5),
        (rotational_diffusivity = 0.035, radius = 0.5), []),
]

function run_scenario(T, motility, kw, extras)
    space = ContinuousSpace((L, L); periodic = true)
    model = StandardABM(T, space, DT;
        properties = Dict(:chemicalfield => CHEMO),
        rng = Xoshiro(1234), container = Vector,
    )
    for _ in 1:NAGENTS
        add_agent!(model; motility = motility(), kw...)
    end
    adata = [xpos, ypos, speed, chemotaxis_bias, chemotaxis_state, extras...]
    adf, = run!(model, NSTEPS; adata, when = 0:10:NSTEPS)
    cols = Symbol.(names(adf))
    keep = filter(c -> c ∉ (:time, :id), cols)
    NamedTuple{Tuple(keep)}(Tuple(Vector{Float64}(adf[!, c]) for c in keep))
end

open(joinpath(@__DIR__, "reference.jl"), "w") do io
    println(io, "# Generated by generate_reference.jl on commit 733ef48. Do not edit.")
    println(io, "const REFERENCE = Dict(")
    for (name, T, motility, kw, extras) in SCENARIOS
        cols = run_scenario(T, motility, kw, extras)
        println(io, "    ", repr(name), " => (")
        for (k, v) in pairs(cols)
            println(io, "        ", k, " = ", repr(v), ",")
        end
        println(io, "    ),")
    end
    println(io, ")")
end
